language: elixir
elixir:
  - 1.10
  - 1.9
  - 1.8
otp_release:
  - 22.3
sudo: false
script: |
  set -ex
  export MIX_ENV=test
  mix deps.get
  mix compile
  mix format --check-formatted
  mix credo
  mix test
  mix coveralls.travis
